### PR TITLE
add m1 support

### PR DESCRIPTION
**Pull request by adracea**

### CODE REVIEW

**Comment by adracea** [comment]
Currently I'm not seeing an option for apple m1 runners so the testing bit won't work on normal macos runners.

**Comment by IchBinLeoon** [comment]
> Currently I'm not seeing an option for apple m1 runners so the testing bit won't work on normal macos runners.

Apparently GitHub-hosted M1 runners are scheduled for Q3 next year: https://github.com/github/roadmap/issues/528

**Comment by l0westbob** [comment]
For the time until the m1 runners are available, you could use the docker compose setup I created to run crunchy-cli in a container https://github.com/l0westbob/crunchy-cli 

I've created this on a m1 machine, and it works like a charm.

**Review by ShivamB25 — APPROVED** [review]

**Comment by ByteDream** [comment]
MacOS arm runners are available as of `2023-10-02` ([github blog entry](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/)) but only as large runners which aren't available for free for public projects. It seems that we have to wait until a version is released we can use (https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587).

**Comment by kennedy** [comment]
I created a pull request for [homebrew-core#152666](https://github.com/Homebrew/homebrew-core/pull/152666). 

It seems they will build, package and host m1 versions (called bottles) in their package repo (example https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fjq)

hopefully it goes through

**Comment by kennedy** [comment]
yay we did it. 

https://github.com/Homebrew/homebrew-core/pull/152666
https://github.com/Homebrew/homebrew-core/pull/152679

https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fcrunchy-cli

**Comment by adracea** [comment]
> yay we did it. 
> 
> https://github.com/Homebrew/homebrew-core/pull/152666
> https://github.com/Homebrew/homebrew-core/pull/152679
> 
> https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fcrunchy-cli

Amazing job dude!

**Comment by ByteDream** [comment]
Yea I think it's pretty much resolved now. Ty @kennedy

**Comment by kgantchev** [comment]
Hi all,

You can use the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's.

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

## 500 mins/month Free for Public Repos

If your repo is public, then FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner.  

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)

**Pull request closed without merging**
