### PR TITLE
Fix FFMPEG audio encoding

### PR DESCRIPTION
**Pull request by DanGLES3**
According to the FFMPEG website this argument (included in the commit) is required when encoding an AAC audio stream from an MPEG-TS file into other formats

https://ffmpeg.org/ffmpeg-bitstream-filters.html#toc-aac_005fadtstoasc

Without this argument the encoded video file will have a longer duration than normal (usually 20-25 seconds more) and will present noticeable audio pops every 3-7 seconds

There might be a better way to implement this as this fix only considers formats related to MP4, so it may be not needed by other formats, however since i do not have much programming experience i'm unable to provide a better alternative, so i at the very least hope this encoding option can be applied to MP4 files

### CODE REVIEW

**Comment by ByteDream** [comment]
Can you provide an episode/series in which the behavior you describe occurs?

**Comment by DanGLES3** [comment]
> Can you provide an episode/series in which the behavior you describe occurs?

One example being Kobayashi's Maid Dragon, there are noticeable pops when playing the audio on VLC and the episode has a longer duration than normal

**Comment by ByteDream** [comment]
I can't reproduce this on my system (Linux) with the latest [v3.0.0-dev.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.2) version (as well as with the old [v2.3.6](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v2.3.6)).
```shell
$ ./crunchy download -o "test.mp4" https://www.crunchyroll.com/watch/GD9UVD04K/the-strongest-maid-in-history-tohru-well-she-is-a-dragon
```

Can you paste your OS + the command you were using for downloading? It can also be a specific ffmpeg issue so your ffmpeg version would also be helpful.

The link you provided also quotes "Please note that it is auto-inserted for MP4A-LATM and MOV/MP4 and related formats.", which I interpret to mean that the option should be automatically applied to mp4 files, regardless of whether the option was (manually) specified or not.

**Comment by DanGLES3** [comment]
> I can't reproduce this on my system (Linux) with the latest [v3.0.0-dev.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.2) version (as well as with the old [v2.3.6](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v2.3.6)).
> 
> ```shell
> $ ./crunchy download -o "test.mp4" https://www.crunchyroll.com/watch/GD9UVD04K/the-strongest-maid-in-history-tohru-well-she-is-a-dragon
> ```
> 
> Can you paste your OS + the command you were using for downloading? It can also be a specific ffmpeg issue so your ffmpeg version would also be helpful.
> 
> The link you provided also quotes "Please note that it is auto-inserted for MP4A-LATM and MOV/MP4 and related formats.", which I interpret to mean that the option should be automatically applied to mp4 files, regardless of whether the option was (manually) specified or not.

Alright, after some testing the issue seems to be present only on version 2.3.6 and not present on version 3

**Pull request closed without merging**
